#!/bin/bash
# =============================================================================
# MedCode AI V16 — Production Setup Script
# =============================================================================
# This script automates the production deployment of MedCode AI.
# Run with: bash scripts/production-setup.sh
# =============================================================================

set -e  # Exit on error
set -u  # Exit on undefined variable

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Helper functions
log_info() {
    echo -e "${BLUE}[INFO]${NC} $1"
}

log_success() {
    echo -e "${GREEN}[SUCCESS]${NC} $1"
}

log_warning() {
    echo -e "${YELLOW}[WARNING]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

# =============================================================================
# Configuration
# =============================================================================
PROJECT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_FILE="${PROJECT_DIR}/.env"
DOCKER_COMPOSE_FILE="${PROJECT_DIR}/docker-compose.prod.yml"
BACKUP_DIR="/opt/medcode/backups"
LOG_DIR="/var/log/medcode"

# =============================================================================
# Pre-flight Checks
# =============================================================================
preflight_checks() {
    log_info "Running pre-flight checks..."
    
    # Check if running as root or with sudo
    if [ "$EUID" -ne 0 ] && [ -z "${SUDO_USER:-}" ]; then
        log_warning "Not running as root. Some operations may require sudo."
    fi
    
    # Check Docker
    if ! command -v docker &> /dev/null; then
        log_error "Docker is not installed."
        exit 1
    fi
    
    # Check Docker Compose
    if ! docker compose version &> /dev/null; then
        log_error "Docker Compose is not installed."
        exit 1
    fi
    
    # Check if .env exists
    if [ ! -f "$ENV_FILE" ]; then
        log_warning ".env file not found. Will create from template."
    fi
    
    log_success "Pre-flight checks passed."
}

# =============================================================================
# Generate Security Keys
# =============================================================================
generate_security_keys() {
    log_info "Generating security keys..."
    
    JWT_SECRET=$(openssl rand -hex 32)
    SECRET_KEY=$(openssl rand -hex 32)
    DB_PASSWORD=$(openssl rand -base64 32)
    REDIS_PASSWORD=$(openssl rand -base64 24)
    
    # Generate Fernet key
    ENCRYPTION_KEY=$(python3 -c "from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())" 2>/dev/null || echo "CHANGE_ME")
    
    log_success "Security keys generated."
}

# =============================================================================
# Create Environment File
# =============================================================================
create_env_file() {
    log_info "Creating .env file..."
    
    if [ -f "$ENV_FILE" ]; then
        log_warning ".env file already exists. Creating backup..."
        cp "$ENV_FILE" "${ENV_FILE}.backup.$(date +%Y%m%d%H%M%S)"
    fi
    
    # Create .env from template with generated values
    cat > "$ENV_FILE" << EOF
# MedCode AI V16 — Production Environment
# Generated by production-setup.sh on $(date)

# ── Application ─────────────────────────────────────────────────────
APP_HOST=0.0.0.0
APP_PORT=8000
APP_ENV=production
LOG_LEVEL=INFO
APP_NAME=MedCode-AI

# ── Database ────────────────────────────────────────────────────────
DATABASE_URL=postgresql://medcode:${DB_PASSWORD}@postgres:5432/medcode
DB_HOST=postgres
DB_PORT=5432
DB_NAME=medcode
DB_USER=medcode
DB_PASSWORD=${DB_PASSWORD}
DB_POOL_SIZE=10
DB_MAX_OVERFLOW=20
DB_POOL_TIMEOUT=30

# ── Redis ───────────────────────────────────────────────────────────
REDIS_URL=redis://redis:6379/0
REDIS_PASSWORD=${REDIS_PASSWORD}
REDIS_MAX_CONNECTIONS=20
REDIS_MAX_MEMORY=256mb

# ── Security ───────────────────────────────────────────────────────
JWT_SECRET=${JWT_SECRET}
SECRET_KEY=${SECRET_KEY}
MEDCODE_ENCRYPTION_KEY=${ENCRYPTION_KEY}
API_KEY_HEADER=X-API-Key
API_KEY_AUTH_ENABLED=true
RATE_LIMIT_PER_MINUTE=100
RATE_LIMIT_BURST=20

# ── HIPAA Compliance ───────────────────────────────────────────────
PHI_MASKING_ENABLED=true
AUDIT_LOG_PATH=/app/logs/audit.log
AUDIT_LOG_RETENTION_DAYS=90

# ── CORS ───────────────────────────────────────────────────────────
CORS_ORIGINS=["https://yourdomain.com"]
CORS_ALLOW_METHODS=["GET","POST","PUT","DELETE","OPTIONS"]
CORS_ALLOW_HEADERS=["Authorization","Content-Type","X-API-Key"]

# ── SSL ────────────────────────────────────────────────────────────
SSL_CERT_PATH=/etc/nginx/ssl/fullchain.pem
SSL_KEY_PATH=/etc/nginx/ssl/privkey.pem

# ── Logging ────────────────────────────────────────────────────────
LOG_FORMAT=json
LOG_FILE=/app/logs/medcode.log
LOG_MAX_SIZE=10485760
LOG_BACKUP_COUNT=30

# ── Feature Flags ──────────────────────────────────────────────────
V16_MODIFIER_ENGINE=true
V16_EM_ENGINE=true
V16_DOC_QUALITY=true
V16_PHYSICIAN_QUERIES=true
V16_MEDICAL_NECESSITY=true
V16_CONTEXT_CLASSIFIER=true
EOF

    chmod 600 "$ENV_FILE"
    log_success ".env file created with permissions 600."
}

# =============================================================================
# Setup SSL Certificates
# =============================================================================
setup_ssl() {
    log_info "Setting up SSL certificates..."
    
    SSL_DIR="${PROJECT_DIR}/nginx/ssl"
    mkdir -p "$SSL_DIR"
    
    # Check if certificates already exist
    if [ -f "${SSL_DIR}/fullchain.pem" ] && [ -f "${SSL_DIR}/privkey.pem" ]; then
        log_success "SSL certificates already exist."
        return
    fi
    
    # Ask user for SSL setup method
    echo ""
    echo "SSL Certificate Setup Options:"
    echo "1) Let's Encrypt (recommended for production)"
    echo "2) Self-signed (for testing only)"
    echo "3) Skip (configure later)"
    echo ""
    read -p "Select option [1-3]: " ssl_option
    
    case $ssl_option in
        1)
            log_info "Setting up Let's Encrypt..."
            read -p "Enter your domain name: " domain_name
            
            if [ -z "$domain_name" ]; then
                log_error "Domain name is required."
                exit 1
            fi
            
            # Install certbot if not present
            if ! command -v certbot &> /dev/null; then
                log_info "Installing certbot..."
                sudo apt update
                sudo apt install -y certbot
            fi
            
            # Get certificate
            log_info "Obtaining SSL certificate..."
            sudo certbot certonly --standalone -d "$domain_name" --non-interactive --agree-tos --email "admin@${domain_name}"
            
            # Copy certificates
            sudo cp "/etc/letsencrypt/live/${domain_name}/fullchain.pem" "${SSL_DIR}/"
            sudo cp "/etc/letsencrypt/live/${domain_name}/privkey.pem" "${SSL_DIR}/"
            sudo chmod 600 "${SSL_DIR}"/*.pem
            
            # Setup auto-renewal
            echo "0 0,12 * * * certbot renew --quiet --post-hook 'docker-compose -f ${DOCKER_COMPOSE_FILE} restart nginx'" | sudo crontab -
            
            log_success "Let's Encrypt SSL setup complete."
            ;;
        2)
            log_info "Generating self-signed certificates..."
            cd "$SSL_DIR"
            bash generate-ssl.sh 2>/dev/null || \
            openssl req -x509 -nodes -days 365 -newkey rsa:2048 \
                -keyout "${SSL_DIR}/privkey.pem" \
                -out "${SSL_DIR}/fullchain.pem" \
                -subj "/C=US/ST=State/L=City/O=MedCode/CN=localhost"
            chmod 600 "${SSL_DIR}"/*.pem
            cd "$PROJECT_DIR"
            log_success "Self-signed certificates generated."
            ;;
        3)
            log_warning "SSL setup skipped. Configure certificates before production use."
            ;;
        *)
            log_error "Invalid option."
            exit 1
            ;;
    esac
}

# =============================================================================
# Setup Database
# =============================================================================
setup_database() {
    log_info "Setting up database..."
    
    # Start PostgreSQL
    log_info "Starting PostgreSQL..."
    docker compose -f "$DOCKER_COMPOSE_FILE" up -d postgres
    
    # Wait for PostgreSQL to be ready
    log_info "Waiting for PostgreSQL to be ready..."
    sleep 10
    
    # Verify PostgreSQL is running
    for i in {1..30}; do
        if docker compose -f "$DOCKER_COMPOSE_FILE" exec -T postgres pg_isready -U medcode -d medcode 2>/dev/null; then
            log_success "PostgreSQL is ready."
            break
        fi
        if [ $i -eq 30 ]; then
            log_error "PostgreSQL failed to start."
            exit 1
        fi
        sleep 2
    done
    
    # Initialize database schema
    log_info "Initializing database schema..."
    docker compose -f "$DOCKER_COMPOSE_FILE" exec -T postgres psql -U medcode -d medcode -f /docker-entrypoint-initdb.d/01-schema.sql 2>/dev/null || \
    log_warning "Schema initialization may have already been applied."
    
    log_success "Database setup complete."
}

# =============================================================================
# Create Admin User
# =============================================================================
create_admin_user() {
    log_info "Creating admin user..."
    
    read -p "Enter admin email [admin@medcode.local]: " admin_email
    admin_email=${admin_email:-admin@medcode.local}
    
    read -s -p "Enter admin password: " admin_password
    echo ""
    
    if [ -z "$admin_password" ]; then
        log_error "Admin password is required."
        exit 1
    fi
    
    # Create admin user
    docker compose -f "$DOCKER_COMPOSE_FILE" exec -T medcode python -c "
from security.auth import create_admin_user
create_admin_user('${admin_email}', '${admin_password}')
print('Admin user created successfully.')
" 2>/dev/null || log_warning "Admin user creation skipped (container may not be running)."
    
    log_success "Admin user setup complete."
}

# =============================================================================
# Setup Backup System
# =============================================================================
setup_backups() {
    log_info "Setting up backup system..."
    
    # Create backup directory
    sudo mkdir -p "$BACKUP_DIR"
    sudo chown "$USER:$USER" "$BACKUP_DIR"
    
    # Create automated backup script
    cat > "${PROJECT_DIR}/scripts/automated-backup.sh" << 'BACKUP_EOF'
#!/bin/bash
BACKUP_DIR="/opt/medcode/backups"
DATE=$(date +%Y%m%d_%H%M%S)
DOCKER_COMPOSE_FILE="/opt/medcode/docker-compose.prod.yml"

# Database backup
docker compose -f "$DOCKER_COMPOSE_FILE" exec -T postgres pg_dump -U medcode medcode | gzip > "$BACKUP_DIR/db_$DATE.sql.gz"

# Application data backup
tar -czf "$BACKUP_DIR/data_$DATE.tar.gz" /opt/medcode/data 2>/dev/null

# Keep only last 30 days
find "$BACKUP_DIR" -name "*.gz" -mtime +30 -delete

echo "Backup completed: $DATE"
BACKUP_EOF
    
    chmod +x "${PROJECT_DIR}/scripts/automated-backup.sh"
    
    # Add to crontab
    (crontab -l 2>/dev/null; echo "0 2 * * * ${PROJECT_DIR}/scripts/automated-backup.sh >> /var/log/medcode/backup.log 2>&1") | crontab -
    
    log_success "Backup system configured."
}

# =============================================================================
# Setup Monitoring
# =============================================================================
setup_monitoring() {
    log_info "Setting up monitoring..."
    
    # Create log directory
    sudo mkdir -p "$LOG_DIR"
    sudo chown "$USER:$USER" "$LOG_DIR"
    
    # Create health monitor script
    cat > "${PROJECT_DIR}/scripts/health-monitor.sh" << 'MONITOR_EOF'
#!/bin/bash
HEALTH_URL="http://localhost/health"
LOG_FILE="/var/log/medcode/health.log"

response=$(curl -s -o /dev/null -w "%{http_code}" "$HEALTH_URL" 2>/dev/null || echo "000")

if [ "$response" != "200" ]; then
    echo "$(date): Health check failed with status $response" >> "$LOG_FILE"
    docker compose -f /opt/medcode/docker-compose.prod.yml restart medcode
fi
MONITOR_EOF
    
    chmod +x "${PROJECT_DIR}/scripts/health-monitor.sh"
    
    # Add to crontab (every 5 minutes)
    (crontab -l 2>/dev/null; echo "*/5 * * * * ${PROJECT_DIR}/scripts/health-monitor.sh") | crontab -
    
    # Setup log rotation
    sudo tee /etc/logrotate.d/medcode > /dev/null << EOF
$LOG_DIR/*.log {
    daily
    missingok
    rotate 90
    compress
    delaycompress
    notifempty
    create 0640 $USER $USER
}
EOF
    
    log_success "Monitoring configured."
}

# =============================================================================
# Build and Deploy Services
# =============================================================================
deploy_services() {
    log_info "Building and deploying services..."
    
    # Build containers
    log_info "Building Docker containers..."
    docker compose -f "$DOCKER_COMPOSE_FILE" build --no-cache
    
    # Start all services
    log_info "Starting services..."
    docker compose -f "$DOCKER_COMPOSE_FILE" up -d
    
    # Wait for services to be ready
    log_info "Waiting for services to be ready..."
    sleep 15
    
    # Verify deployment
    log_info "Verifying deployment..."
    for i in {1..30}; do
        response=$(curl -s -o /dev/null -w "%{http_code}" http://localhost/health 2>/dev/null || echo "000")
        if [ "$response" = "200" ]; then
            log_success "Application is healthy."
            break
        fi
        if [ $i -eq 30 ]; then
            log_warning "Health check timeout. Check logs for details."
        fi
        sleep 2
    done
    
    # Show running containers
    docker compose -f "$DOCKER_COMPOSE_FILE" ps
    
    log_success "Deployment complete."
}

# =============================================================================
# Print Summary
# =============================================================================
print_summary() {
    echo ""
    echo "=========================================="
    echo "  MedCode AI V16 — Deployment Complete"
    echo "=========================================="
    echo ""
    echo "Access Points:"
    echo "  - API: http://localhost:8000/docs"
    echo "  - Dashboard: http://localhost:8000/dashboard/"
    echo "  - Health: http://localhost/health"
    echo ""
    echo "Important Files:"
    echo "  - Environment: ${ENV_FILE}"
    echo "  - Docker Compose: ${DOCKER_COMPOSE_FILE}"
    echo "  - Backups: ${BACKUP_DIR}"
    echo "  - Logs: ${LOG_DIR}"
    echo ""
    echo "Next Steps:"
    echo "  1. Update CORS_ORIGINS in .env with your domain"
    echo "  2. Configure ANTHROPIC_API_KEY if using AI features"
    echo "  3. Test the deployment: curl http://localhost/health"
    echo "  4. Review logs: docker compose -f ${DOCKER_COMPOSE_FILE} logs -f"
    echo ""
    echo "Security Notes:"
    echo "  - Keep .env file secure (chmod 600)"
    echo "  - Rotate secrets regularly"
    echo "  - Monitor access logs"
    echo ""
}

# =============================================================================
# Main Execution
# =============================================================================
main() {
    echo "=========================================="
    echo "  MedCode AI V16 — Production Setup"
    echo "=========================================="
    echo ""
    
    preflight_checks
    generate_security_keys
    create_env_file
    setup_ssl
    setup_database
    create_admin_user
    setup_backups
    setup_monitoring
    deploy_services
    print_summary
}

# Run main function
main "$@"
