"""
MedCode AI V19 — Real-Time Security Monitoring
================================================
HIPAA §164.308(a)(1)(ii)(D) — Information System Activity Review.

Provides real-time threat detection:
  - Brute force detection
  - Anomalous access patterns
  - PHI exfiltration detection
  - Unauthorized endpoint access
"""

from __future__ import annotations

import time
from collections import defaultdict
from dataclasses import dataclass, field
from datetime import datetime, timezone
from typing import Dict, List, Optional


@dataclass
class SecurityAlert:
    """A security alert generated by the monitor."""
    alert_id: str = ""
    alert_type: str = ""
    severity: str = "low"
    message: str = ""
    user_id: str = ""
    ip_address: str = ""
    timestamp: str = ""
    details: Dict[str, any] = field(default_factory=dict)

    def to_dict(self) -> dict:
        return {
            "alert_id": self.alert_id,
            "alert_type": self.alert_type,
            "severity": self.severity,
            "message": self.message,
            "user_id": self.user_id,
            "ip_address": self.ip_address,
            "timestamp": self.timestamp,
        }


class SecurityMonitor:
    """
    Real-time security monitoring and threat detection.
    
    Detects:
      - Brute force login attempts (>5 failures in 5 min)
      - Anomalous access patterns
      - Large data exports
      - Unauthorized endpoint access
      - PHI access anomalies
    """

    def __init__(
        self,
        brute_force_threshold: int = 5,
        brute_force_window: int = 300,
        large_export_threshold: int = 100,
    ):
        self._brute_force_threshold = brute_force_threshold
        self._brute_force_window = brute_force_window
        self._large_export_threshold = large_export_threshold
        
        self._alerts: List[SecurityAlert] = []
        self._login_attempts: Dict[str, List[float]] = defaultdict(list)
        self._access_patterns: Dict[str, List[str]] = defaultdict(list)
        self._locked_accounts: Dict[str, float] = {}
        self._alert_counter = 0

    def _create_alert(
        self,
        alert_type: str,
        severity: str,
        message: str,
        user_id: str = "",
        ip_address: str = "",
        details: Optional[Dict] = None,
    ) -> SecurityAlert:
        self._alert_counter += 1
        alert = SecurityAlert(
            alert_id=f"SA-{self._alert_counter:06d}",
            alert_type=alert_type,
            severity=severity,
            message=message,
            user_id=user_id,
            ip_address=ip_address,
            timestamp=datetime.now(timezone.utc).isoformat(),
            details=details or {},
        )
        self._alerts.append(alert)
        return alert

    def record_login_attempt(
        self,
        user_id: str,
        ip_address: str,
        success: bool,
    ) -> Optional[SecurityAlert]:
        """Record a login attempt and check for brute force."""
        now = time.time()
        
        if not success:
            self._login_attempts[f"{user_id}:{ip_address}"].append(now)
            
            attempts = self._login_attempts[f"{user_id}:{ip_address}"]
            attempts = [t for t in attempts if now - t < self._brute_force_window]
            self._login_attempts[f"{user_id}:{ip_address}"] = attempts
            
            if len(attempts) >= self._brute_force_threshold:
                self._locked_accounts[user_id] = now + 900
                return self._create_alert(
                    alert_type="brute_force",
                    severity="critical",
                    message=f"Brute force detected: {len(attempts)} failed logins from {ip_address}",
                    user_id=user_id,
                    ip_address=ip_address,
                    details={"attempts": len(attempts), "locked_until": self._locked_accounts[user_id]},
                )
        else:
            self._login_attempts.pop(f"{user_id}:{ip_address}", None)
        
        return None

    def is_account_locked(self, user_id: str) -> bool:
        """Check if an account is temporarily locked."""
        locked_until = self._locked_accounts.get(user_id, 0)
        if time.time() < locked_until:
            return True
        self._locked_accounts.pop(user_id, None)
        return False

    def record_data_export(
        self,
        user_id: str,
        record_count: int,
        resource_type: str = "",
    ) -> Optional[SecurityAlert]:
        """Record a data export and check for anomalies."""
        if record_count >= self._large_export_threshold:
            return self._create_alert(
                alert_type="large_export",
                severity="high",
                message=f"Large data export: {record_count} records by {user_id}",
                user_id=user_id,
                details={"record_count": record_count, "resource_type": resource_type},
            )
        return None

    def record_phi_access(
        self,
        user_id: str,
        note_id: str,
        access_type: str,
        ip_address: str = "",
    ) -> Optional[SecurityAlert]:
        """Record PHI access and check for anomalies."""
        pattern_key = f"{user_id}:{note_id}"
        self._access_patterns[pattern_key].append(access_type)
        
        access_count = len(self._access_patterns[pattern_key])
        if access_count > 20:
            return self._create_alert(
                alert_type="phi_access_anomaly",
                severity="medium",
                message=f"Excessive PHI access: {access_count} accesses to note {note_id}",
                user_id=user_id,
                ip_address=ip_address,
                details={"access_count": access_count, "note_id": note_id},
            )
        return None

    def record_endpoint_access(
        self,
        user_id: str,
        endpoint: str,
        status_code: int,
        ip_address: str = "",
    ) -> Optional[SecurityAlert]:
        """Record endpoint access and check for unauthorized patterns."""
        if status_code == 403:
            return self._create_alert(
                alert_type="unauthorized_access",
                severity="medium",
                message=f"Unauthorized access attempt to {endpoint}",
                user_id=user_id,
                ip_address=ip_address,
                details={"endpoint": endpoint, "status_code": status_code},
            )
        
        if status_code == 404 and "/api/" in endpoint:
            return self._create_alert(
                alert_type="endpoint_enumeration",
                severity="low",
                message=f"Possible endpoint enumeration: 404 on {endpoint}",
                ip_address=ip_address,
                details={"endpoint": endpoint},
            )
        
        return None

    def get_alerts(
        self,
        severity: Optional[str] = None,
        alert_type: Optional[str] = None,
        limit: int = 50,
    ) -> List[SecurityAlert]:
        """Get alerts with optional filters."""
        filtered = self._alerts
        if severity:
            filtered = [a for a in filtered if a.severity == severity]
        if alert_type:
            filtered = [a for a in filtered if a.alert_type == alert_type]
        return filtered[-limit:]

    def get_critical_alerts(self) -> List[SecurityAlert]:
        """Get all critical alerts."""
        return [a for a in self._alerts if a.severity == "critical"]

    def has_critical_alerts(self) -> bool:
        """Check if there are any critical alerts."""
        return any(a.severity == "critical" for a in self._alerts)

    def get_stats(self) -> dict:
        return {
            "total_alerts": len(self._alerts),
            "critical_alerts": len([a for a in self._alerts if a.severity == "critical"]),
            "high_alerts": len([a for a in self._alerts if a.severity == "high"]),
            "locked_accounts": len(self._locked_accounts),
            "alert_types": list(set(a.alert_type for a in self._alerts)),
        }


_monitor: Optional[SecurityMonitor] = None


def get_security_monitor() -> SecurityMonitor:
    global _monitor
    if _monitor is None:
        _monitor = SecurityMonitor()
    return _monitor
